# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.232.129:22122
  web-server-url: 192.168.232.129:8888 #文件下载地址
  pool:
    max-total: 153 #从池中借出的对象的最大数目
    max-wait-millis: 102 #获取连接时的最大等待毫秒数100

#security:
#  user:
#    name: admin
#    password: admin
spring:
  http:
    multipart:
      max-file-size: 200Mb #设置上传文件的最大大小
      max-request-size: 10Mb #设置请求的最大大小
  thymeleaf:
    enabled: false #必须将模板设为不可用，以下路径配置才有效
  mvc:
    view:
      suffix: .html
      # 定位页面的目录到static/下
      prefix: /
  boot:
     admin:
       url: http://localhost:8080
       client:
         name: fscore
logging:
  config: classpath:logback.xml
server:
  port: 8081
management:
  security:
    #关闭Actuator监控权限
    enabled: false
